<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class DWSMontage
{
    private $dws_montage_options;

    public function __construct()
    {
        add_action('admin_menu', array($this, 'dws_montage_add_plugin_page'));
        add_action('admin_init', array($this, 'dws_montage_page_init'));
    }

    public function dws_montage_add_plugin_page()
    {
        add_menu_page(
            'DWS Montage', // page_title
            'DWS Montage', // menu_title
            'manage_options', // capability
            'dws-montage', // menu_slug
            array($this, 'dws_montage_create_admin_page'), // function
            'dashicons-admin-generic', // icon_url
            2 // position
        );
    }

    public function dws_montage_create_admin_page()
    {
        $this->dws_montage_options = get_option('dws_montage_option_name'); ?>

        <div class="wrap">
            <h2>DWS Montage</h2>
            <p></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields('dws_montage_option_group');
                do_settings_sections('dws-montage-admin');
                do_settings_sections('dws-woo-custom-id-admin');
                submit_button();
                ?>
            </form>
        </div>
<?php }

    public function dws_montage_page_init()
    {
        register_setting(
            'dws_montage_option_group', // option_group
            'dws_montage_option_name', // option_name
            array($this, 'dws_montage_sanitize') // sanitize_callback
        );

        add_settings_section(
            'dws_montage_setting_section', // id
            'AWS', // title
            array($this, 'dws_montage_section_info'), // callback
            'dws-montage-admin' // page
        );

        add_settings_field(
            's3_access_key_0', // id
            'S3 Access Key', // title
            array($this, 's3_access_key_0_callback'), // callback
            'dws-montage-admin', // page
            'dws_montage_setting_section' // section
        );

        add_settings_field(
            's3_secret_1', // id
            'S3 Secret', // title
            array($this, 's3_secret_1_callback'), // callback
            'dws-montage-admin', // page
            'dws_montage_setting_section' // section
        );

        add_settings_field(
            's3_bucket_2', // id
            'S3 Bucket', // title
            array($this, 's3_bucket_2_callback'), // callback
            'dws-montage-admin', // page
            'dws_montage_setting_section' // section
        );

        add_settings_field(
            's3_region_3', // id
            'S3 Region', // title
            array($this, 's3_region_3_callback'), // callback
            'dws-montage-admin', // page
            'dws_montage_setting_section' // section
        );

        add_settings_section(
            'dws_woo_custom_id_setting_section',
            'Order ID',
            array($this, 'dws_woo_custom_id_section_info'),
            'dws-montage-admin'
        );

        add_settings_field(
            'jelenlegi_id_0',
            'Jelenlegi ID',
            array($this, 'jelenlegi_id_0_callback'),
            'dws-montage-admin',
            'dws_woo_custom_id_setting_section'
        );

        add_settings_field(
            'kategoria_id_k_1',
            'Kategória ID-k',
            array($this, 'kategoria_id_k_1_callback'),
            'dws-montage-admin',
            'dws_woo_custom_id_setting_section'
        );

        add_settings_section(
            'dws_montage_filetype_quality_section', // id
            'File Settings', // title
            array($this, 'dws_montage_filetype_quality_section_info'), // callback
            'dws-montage-admin' // page
        );

        add_settings_field(
            'filetype', // id
            'Filetype', // title
            array($this, 'filetype_callback'), // callback
            'dws-montage-admin', // page
            'dws_montage_filetype_quality_section' // section
        );

        add_settings_field(
            'quality', // id
            'Quality', // title
            array($this, 'quality_callback'), // callback
            'dws-montage-admin', // page
            'dws_montage_filetype_quality_section' // section
        );
    }

    public function dws_montage_sanitize($input)
    {
        $sanitary_values = array();
        if (isset($input['s3_access_key_0'])) {
            $sanitary_values['s3_access_key_0'] = sanitize_text_field($input['s3_access_key_0']);
        }

        if (isset($input['s3_secret_1'])) {
            $sanitary_values['s3_secret_1'] = sanitize_text_field($input['s3_secret_1']);
        }

        if (isset($input['s3_bucket_2'])) {
            $sanitary_values['s3_bucket_2'] = sanitize_text_field($input['s3_bucket_2']);
        }

        if (isset($input['s3_region_3'])) {
            $sanitary_values['s3_region_3'] = sanitize_text_field($input['s3_region_3']);
        }

        if (isset($input['jelenlegi_id_0'])) {
            $sanitary_values['jelenlegi_id_0'] = sanitize_text_field($input['jelenlegi_id_0']);
        }

        if (isset($input['kategoria_id_k_1'])) {
            $sanitary_values['kategoria_id_k_1'] = sanitize_text_field($input['kategoria_id_k_1']);
        }

        if (isset($input['filetype'])) {
            $valid_filetypes = ['png', 'jpeg', 'webp'];
            if (in_array($input['filetype'], $valid_filetypes)) {
                $sanitary_values['filetype'] = sanitize_text_field($input['filetype']);
            }
        }

        if (isset($input['quality'])) {
            $quality = intval($input['quality']);
            if ($quality >= 1 && $quality <= 100) {
                $sanitary_values['quality'] = $quality;
            }
        }

        return $sanitary_values;
    }

    public function dws_montage_section_info() {}

    public function s3_access_key_0_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="dws_montage_option_name[s3_access_key_0]" id="s3_access_key_0" value="%s">',
            isset($this->dws_montage_options['s3_access_key_0']) ? esc_attr($this->dws_montage_options['s3_access_key_0']) : ''
        );
    }

    public function s3_secret_1_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="dws_montage_option_name[s3_secret_1]" id="s3_secret_1" value="%s">',
            isset($this->dws_montage_options['s3_secret_1']) ? esc_attr($this->dws_montage_options['s3_secret_1']) : ''
        );
    }

    public function s3_bucket_2_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="dws_montage_option_name[s3_bucket_2]" id="s3_bucket_2" value="%s">',
            isset($this->dws_montage_options['s3_bucket_2']) ? esc_attr($this->dws_montage_options['s3_bucket_2']) : ''
        );
    }

    public function s3_region_3_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="dws_montage_option_name[s3_region_3]" id="s3_region_3" value="%s">',
            isset($this->dws_montage_options['s3_region_3']) ? esc_attr($this->dws_montage_options['s3_region_3']) : ''
        );
    }

    public function dws_woo_custom_id_section_info() {}

    public function jelenlegi_id_0_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="dws_montage_option_name[jelenlegi_id_0]" id="jelenlegi_id_0" value="%s">',
            isset($this->dws_montage_options['jelenlegi_id_0']) ? esc_attr($this->dws_montage_options['jelenlegi_id_0']) : ''
        );
    }

    public function kategoria_id_k_1_callback()
    {
        printf(
            '<input class="regular-text" type="text" name="dws_montage_option_name[kategoria_id_k_1]" id="kategoria_id_k_1" value="%s">',
            isset($this->dws_montage_options['kategoria_id_k_1']) ? esc_attr($this->dws_montage_options['kategoria_id_k_1']) : ''
        );
    }

    public function dws_montage_filetype_quality_section_info() {}

    public function filetype_callback()
    {
        $options = ['png', 'jpeg', 'webp']; // Dropdown options
        $current_value = isset($this->dws_montage_options['filetype']) ? $this->dws_montage_options['filetype'] : '';

        echo '<select name="dws_montage_option_name[filetype]" id="filetype">';
        foreach ($options as $option) {
            $selected = ($current_value === $option) ? 'selected="selected"' : '';
            printf('<option value="%s" %s>%s</option>', esc_attr($option), $selected, strtoupper($option));
        }
        echo '</select>';
    }

    public function quality_callback()
    {
        $current_value = isset($this->dws_montage_options['quality']) ? $this->dws_montage_options['quality'] : '';
        printf(
            '<input class="regular-text" type="number" name="dws_montage_option_name[quality]" id="quality" value="%s" min="1" max="100">',
            esc_attr($current_value)
        );
    }
}
if (is_admin())
    $dws_montage = new DWSMontage();

/* 
 * Retrieve this value with:
 * $dws_montage_options = get_option( 'dws_montage_option_name' ); // Array of All Options
 * $s3_access_key_0 = $dws_montage_options['s3_access_key_0']; // S3 Access Key
 * $s3_secret_1 = $dws_montage_options['s3_secret_1']; // S3 Secret
 * $s3_bucket_2 = $dws_montage_options['s3_bucket_2']; // S3 Bucket
 * $s3_region_3 = $dws_montage_options['s3_region_3']; // S3 Region
 */
